version: '3'

services:
  db:
    image: mariadb:10.7-focal
    container_name: db-sgd
    restart: always
    # env_file:
    #   - .env
    environment:
      # MARIADB_DATABASE: ${MARIADB_DATABASE}
      # MARIADB_USER: ${MARIADB_USER}
      # MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      # MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: sgd
      MARIADB_USER: sgd-admin
      MARIADB_PASSWORD: kdfhgkjfsue84535f_UGj47
      MARIADB_ROOT_PASSWORD: root_kdfhgkjfsue84535f_UGj47__OW4
    ports:
      - 5000:3306
    expose:
      - "3306"
    networks:
      - sgd-dev-net

networks:
  sgd-dev-net:
    driver: bridge

