# Generated by Django 3.2.16 on 2022-12-25 20:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('initials', models.CharField(max_length=15)),
                ('percent', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_name_real_life', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outros')], default='F', max_length=1)),
                ('cep', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=11)),
                ('prof_pic', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('D', 'Depósito'), ('S', 'Saque'), ('T', 'Transferência'), ('OD', 'Outros descontos')], default='D', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=10, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgdapi.account')),
                ('send_to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_to_account', to='sgdapi.account')),
                ('send_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_to_user', to='sgdapi.accountholder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgdapi.accountholder')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgdapi.accountholder'),
        ),
    ]
