# Generated by Django 3.2.13 on 2022-06-14 00:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('initials', models.CharField(max_length=7)),
                ('percent', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_name_real_life', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=30)),
                ('nick_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outros')], default='F', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('D', 'Depósito'), ('S', 'Saque'), ('T', 'Transferência'), ('OD', 'Outros descontos')], default='D', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgdapi.account')),
                ('send_to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_to_account', to='sgdapi.accountholder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgdapi.accountholder')),
            ],
        ),
    ]
