# Generated by Django 3.2.16 on 2022-12-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='sex',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outros')], default='F', max_length=1, null=True),
        ),
    ]
