# Generated by Django 3.2.13 on 2022-06-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='user_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
