# Generated by Django 3.2.13 on 2022-06-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0002_auto_20220614_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default='janderson.araujo', on_delete=django.db.models.deletion.CASCADE, to='sgdapi.accountholder'),
            preserve_default=False,
        ),
    ]
