# Generated by Django 3.2.16 on 2022-12-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0002_auto_20221231_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='cep',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
