# Generated by Django 3.2.13 on 2022-06-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0003_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='cep',
            field=models.CharField(default='06835390', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountholder',
            name='city',
            field=models.CharField(default='Embu das Artes', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountholder',
            name='number',
            field=models.IntegerField(default=454),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountholder',
            name='phone',
            field=models.CharField(default='11983864021', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountholder',
            name='state',
            field=models.CharField(default='SP', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountholder',
            name='street',
            field=models.CharField(default='Avenida Hercílio Wustemberg', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
