# Generated by Django 3.2.13 on 2022-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0004_auto_20220616_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='district',
            field=models.CharField(default='Jardim Pinheirinho', max_length=50),
            preserve_default=False,
        ),
    ]
