# Generated by Django 3.2.16 on 2023-01-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0005_transaction_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_by', models.JSONField()),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('event', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
