# Generated by Django 3.2.13 on 2022-07-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0006_accountholder_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='prof_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
