# Generated by Django 3.2.16 on 2023-01-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0006_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
