# Generated by Django 3.2.13 on 2022-07-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0007_alter_accountholder_prof_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
