# Generated by Django 3.2.13 on 2022-07-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0008_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='initials',
            field=models.CharField(max_length=15),
        ),
    ]
