# Generated by Django 3.2.13 on 2022-07-05 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgdapi', '0009_alter_account_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='send_to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_to_account', to='sgdapi.account'),
        ),
    ]
